config/routes.rb
Oscartes::Application.routes.draw do
  resources :user_sessions

  resources :users

  resources :albums

  resources :images

  resources :news

  root :to => "static#convite"

  
  match 'inicio' => 'static#index'
  
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  
  match 'albuns' => 'static#albuns'
  match 'noticias' => 'static#noticias'
  match 'eventos' => 'static#eventos'
  
  match 'albuns/:id' => 'static#imagens'
  
  match 'noticias/:id' => 'static#noticia'
  
  match 'imagem/:id' => 'static#imagem'
  
end

app/models/news.rb
# encoding: utf-8

class News < ActiveRecord::Base
  validates_presence_of :titulo, :texto, :message => "não pode estar em branco"
end

app/controllers/news_controller.rb
# encoding: utf-8

class NewsController < ApplicationController

  before_filter :authentication

  # GET /news
  # GET /news.xml
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/1
  # GET /news/1.xml
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/new
  # GET /news/new.xml
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.xml
  def create
    @news = News.new(params[:news])
    @news.update_attributes("data" => Time.now)

    respond_to do |format|
      if @news.save
        format.html { redirect_to(news_index_url, :notice => 'Notícia criada com sucesso.') }
        format.xml  { render :xml => @news, :status => :created, :location => @news }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @news.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.xml
  def update
    @news = News.find(params[:id])
    @news.update_attributes("data" => Time.now)

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to(news_index_url, :notice => 'Notícia atualizada com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @news.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.xml
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to(news_index_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "erro") %> proíbem a notícia de ser salva:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label 'Título' %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label 'Texto' %><br />
    <%= f.text_area :texto %>
  </div>
  <div class="actions">
    <%= f.submit submit_label %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editar Notícias</h1>

<%= render :partial => 'form', :locals => {:submit_label => 'Editar'} %>

<%= link_to 'Voltar', :back %>

app/views/news/index.html.erb
<h1>Notícias</h1>

<table>
  <tr>
    <th>Título</th>
    <th>Texto</th>
    <th>Data</th>
    <th></th>
    <th></th>
  </tr>

<% @news.each do |news| %>
  <tr>
    <td><%= link_to news.titulo, news %></td>
    <td><%= news.texto[0..21]+"…" %></td>
    <td><%= date_format(news.data) %></td>
    <td><%= link_to 'Editar', edit_news_path(news) %></td>
    <td><%= link_to 'Apagar', news, :confirm => 'Tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Inserir Notícia', new_news_path %>

app/views/news/new.html.erb
<h1>Inserir Notícia</h1>

<%= render :partial => 'form', :locals => {:submit_label => 'Inserir'} %>

<%= link_to 'Voltar', :back %>

app/views/news/show.html.erb
<p>
  <b>Título:</b>
  <%= @news.titulo %>
</p>

<b>Texto:</b>
<%= simple_format auto_link @news.texto %>

<p>
  <b>Data:</b>
  <%= date_format(@news.data) %>
</p>


<%= link_to 'Editar', edit_news_path(@news) %> |
<%= link_to 'Voltar', :back %>