config/routes.rb
Oscartes::Application.routes.draw do
  resources :user_sessions

  resources :users

  resources :albums

  resources :images

  resources :news

  root :to => "static#convite"

  
  match 'inicio' => 'static#index'
  
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  
  match 'albuns' => 'static#albuns'
  match 'noticias' => 'static#noticias'
  match 'eventos' => 'static#eventos'
  
  match 'albuns/:id' => 'static#imagens'
  
  match 'noticias/:id' => 'static#noticia'
  
  match 'imagem/:id' => 'static#imagem'
  
end

app/models/album.rb
# encoding: utf-8

class Album < ActiveRecord::Base
  validates_presence_of :titulo, :descricao, :tipo, :message => "não pode estar em branco"
  
  has_many :images, :dependent => :destroy
  
  # Selects the last updated image on the current album
  def self.find_one_image(id)
    Image.find_by_album_id(id).photo.url(:small)
  end
end

app/controllers/albums_controller.rb
# encoding: utf-8

class AlbumsController < ApplicationController

  before_filter :authentication

  # GET /albums
  # GET /albums.xml
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.xml
  def show
    @album = Album.find(params[:id])
    @images = Image.find_all_by_album_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.xml
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.xml
  def create
    @album = Album.new(params[:album])
    @album.update_attributes("data" => Time.now)

    respond_to do |format|
      if @album.save
        format.html { redirect_to(albums_url, :notice => 'Álbum criado com sucesso.') }
        format.xml  { render :xml => @album, :status => :created, :location => @album }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.xml
  def update
    @album = Album.find(params[:id])
    @album.update_attributes("data" => Time.now)

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to(albums_url, :notice => 'Álbum atualizado com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.xml
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to(albums_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "erro") %> proíbem o álbum de ser salvo:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Título' %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label 'Descrição' %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label 'Tipo' %><br />
    <%= f.select('tipo', {"Gravura" => "Gravura", "Pintura" => "Pintura", "Desenho" => "Desenho", "Evento" => "Evento"}, {:include_blank => true}) %>
  </div>
  <div class="actions">
    <%= f.submit submit_label %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editar Álbum</h1>

<%= render :partial => 'form', :locals => {:submit_label => 'Editar'} %>

<%= link_to 'Voltar', :back %>

app/views/albums/index.html.erb
<h1>Álbums</h1>

<table>
  <tr>
    <th>Título</th>
    <th>Descrição</th>
    <th>Data</th>
    <th>Tipo</th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= link_to album.titulo, album %></td>
    <td><%= album.descricao[0..20]+"..." %></td>
    <td><%= date_format(album.data) %></td>
    <td><%= album.tipo %></td>
    <td><%= link_to 'Editar', edit_album_path(album) %></td>
    <td><%= link_to 'Apagar', album, :confirm => 'Tem certeza? Todas as imagens associadas a esse Álbum serão apagadas.', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Inserir Álbum', new_album_path %>

app/views/albums/new.html.erb
<h1>Inserir Álbum</h1>

<%= render :partial => 'form', :locals => {:submit_label => 'Inserir'} %>

<%= link_to 'Voltar', :back %>

app/views/albums/show.html.erb
<p>
  <b>Título:</b>
  <%= @album.titulo %>
</p>

<p>
  <b>Descrição:</b>
  <%= @album.descricao %>
</p>

<p>
  <b>Data:</b>
  <%= date_format(@album.data) %>
</p>

<p>
  <b>Tipo:</b>
  <%= @album.tipo %>
</p>

<p>
  <b>Imagens do Álbum:</b>
  <br />
  <% @images.each do |image| %>
    <%= image_tag image.photo.url(:small) %>
  <% end %>
</p>


<%= link_to 'Editar', edit_album_path(@album) %> |
<%= link_to 'Voltar', :back %>