config/routes.rb
Oscartes::Application.routes.draw do
  resources :user_sessions

  resources :users

  resources :albums

  resources :images

  resources :news

  root :to => "static#convite"

  
  match 'inicio' => 'static#index'
  
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  
  match 'albuns' => 'static#albuns'
  match 'noticias' => 'static#noticias'
  match 'eventos' => 'static#eventos'
  
  match 'albuns/:id' => 'static#imagens'
  
  match 'noticias/:id' => 'static#noticia'
  
  match 'imagem/:id' => 'static#imagem'
  
end

app/models/image.rb
# encoding: utf-8

class Image < ActiveRecord::Base
  validates_presence_of :title, :album, :message => "não pode estar em branco"
  
  validates_attachment_presence :photo, :message => "não pode estar em branco"
  validates_attachment_size :photo, :less_than => 10.megabytes, :message => "não pode ter mais de 10MB"
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/bmp']
  
  has_attached_file :photo, :styles => { 
  										:small => {  :geometry => "120x120>", :format => 'JPG'},
  										:medium => { :geometry => "960x480#", :format => 'JPG'}
  										},
  										 			  
  							:convert_options => { :small => '-quality 50', :medium => '-quality 60' }
  
  belongs_to :album
end

app/controllers/images_controller.rb
# encoding: utf-8

class ImagesController < ApplicationController

  before_filter :authentication

  # GET /images
  # GET /images.xml
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @images }
    end
  end

  # GET /images/1
  # GET /images/1.xml
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/new
  # GET /images/new.xml
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.xml
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to(images_url, :notice => 'Imagem criada com sucesso.') }
        format.xml  { render :xml => @image, :status => :created, :location => @image }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to(images_url, :notice => 'Imagem atualizada com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to(images_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/images_helper.rb
# encoding: utf-8

module ImagesHelper
  def visivel_no_site(visivel)
    if visivel
      return "Sim"
    else
      return "Não"
    end
  end
end

app/views/images/_form.html.erb
<%= form_for(@image, :html => {:multipart => true}) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "erro") %> proíbem a imagem de ser salva:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Título' %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label 'Álbum' %><br />
    <%= f.collection_select(:album_id, Album.all, :id, :titulo) %>
  </div>
  <div class="field">
    <%= f.label 'Foto' %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label 'Visivel na página inicial?' %><br />
    <%= f.check_box :visivel %> Sim
  </div>
  <div class="actions">
    <%= f.submit submit_label %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editar Imagem</h1>

<%= render :partial => 'form', :locals => {:submit_label => 'Editar'} %>

<%= link_to 'Voltar', :back %>

app/views/images/index.html.erb
<h1>Imagens</h1>

<table>
  <tr>
    <th>Título</th>
    <th>Álbum</th>
    <th>Data</th>
    <th>Visível no Site?</th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= link_to image.title, image %></td>
    <td><%= Album.find_by_id(image.album_id).titulo %></td>
    <td><%= date_format(image.updated_at) %></td>
    <td><%= visivel_no_site(image.visivel) %></td>
    <td><%= link_to 'Editar', edit_image_path(image) %></td>
    <td><%= link_to 'Apagar', image, :confirm => 'Tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Inserir Imagem', new_image_path %>

app/views/images/new.html.erb
<h1>Inserir Imagem</h1>

<%= render :partial => 'form', :locals => {:submit_label => 'Adicionar'} %>

<%= link_to 'Voltar', :back %>

app/views/images/show.html.erb
<p>
  <b>Título:</b>
  <%= @image.title %>
</p>

<p>
  <b>Imagem:</b><br />
  <%= image_tag @image.photo.url(:small) %>
</p>

<p>
  <b>Data:</b>
  <%= date_format(@image.updated_at) %>
</p>

<p>
  Visivel na página inicial?<br />
  <%= visivel_no_site(@image.visivel) %>
</p>

<%= link_to 'Editar', edit_image_path(@image) %> |
<%= link_to 'Voltar', :back %>